### ISSUE TITLE
Guia de lenguajes 101

### ISSUE THREAD

**Issue by karengrams** [karengrams/FinalesDeParadigmasDeProgramacion#10]
https://github.com/karengrams/FinalesDeParadigmasDeProgramacion/blob/c3ca92361c29dc6287ba92303f05d91f27b0dcf5/27%20de%20septimebre%20del%202017/270917.hs#L60-L63

¡head no existe en prolog! Y fijate de usar el predicado del punto anterior.

**Comment by PabloOve** [comment]
flasheada mia, es cierto jajaja
