### ISSUE TITLE
¡Orden superior!

### ISSUE THREAD

**Issue by karengrams** [karengrams/FinalesDeParadigmasDeProgramacion#12]
https://github.com/karengrams/FinalesDeParadigmasDeProgramacion/blob/6dc153659be10b2f975789255925165405241b21/15%20de%20julio%20del%202017/150717.hs#L4-L6

La función "flip" recibe una función como parámetro, ahi podriamos explicar el concepto de orden superior.

**Comment by PabloOve** [comment]
Right
