### ISSUE TITLE
Don't hurry

### ISSUE THREAD

**Issue by karengrams** [karengrams/FinalesDeParadigmasDeProgramacion#16]
https://github.com/karengrams/FinalesDeParadigmasDeProgramacion/blob/6dc153659be10b2f975789255925165405241b21/15%20de%20julio%20del%202017/150717.hs#L24-L25

No se si colocaría en la respuesta la forma en que se resuelve, hay múltiples formas de resolverlo, iría mas al "Falso. _Respuesta_" o al "Verdadero. _Respuesta_".
¿Por que menciono esto? Well,

> Matías Sanchez (alumno):
> d. Verdadero, porque no todos los clientes son jubilados y este campo no aplicaría para todos. Debería ir en una subclase Jubilado que herede de Cliente.
> [Matías Freyre](https://groups.yahoo.com/neo/groups/pdep/conversations/messages/9057) (profesor):
> OK, pero **cuidado** con lo que mencioné sobre la clase Cliente, podría ser simplemente un tipo... o no. De hecho, vos no lo modelaste en tu solución, pero en tu caso es un error porque te faltó un pedazo de código, justamente el código del cliente, para que no se rompa todo cuando mandás el mensaje "precioDeVentaDe: para:" desde la farmacia a un cliente que no es jubilado ni discapacitado (fijate que el código del enunciado tiene un descuento de 0 para esos casos, cosa que en tu solución no figura).

Recomiendo que leas bien todo lo que se hablo ahí, te ubica un poco como corrigen los profes.

**Comment by PabloOve** [comment]
Uyy, importante saber esto! Gracias por el dato!
