### ISSUE TITLE
Warning: [ ] vs #{ }

### ISSUE THREAD

**Issue by karengrams** [karengrams/FinalesDeParadigmasDeProgramacion#19]
https://github.com/karengrams/FinalesDeParadigmasDeProgramacion/blob/6dc153659be10b2f975789255925165405241b21/15%20de%20julio%20del%202017/150717.hs#L31

Santi siempre observaba si era un set o una lista, ¿un cliente puede tener dos veces el mismo producto? Lo preguntaría en el final, pero, puse un set por las dudas.

**Comment by PabloOve** [comment]
ciertoo, hasta habia un parcial de santi que habia un set de productos
