### ISSUE TITLE
Menos código, ¿mejor o peor? 

### ISSUE THREAD

**Issue by karengrams** [karengrams/FinalesDeParadigmasDeProgramacion#2]
https://github.com/karengrams/FinalesDeParadigmasDeProgramacion/blob/c3ca92361c29dc6287ba92303f05d91f27b0dcf5/27%20de%20septimebre%20del%202017/270917.hs#L9

No se si decir que tener menos codigo es mejor que mucho codigo, haria referencia mas al proceso algoritmico que deja a simple vista la solucion propuesta, a decir que codear menos es mejor. 
Santi, en cadi todas las correcione, me preguntaba "¿por que queres codear menos?¿sacas algo de ventaja con eso?". **_Mind blowing_**.

**Comment by PabloOve** [comment]
Lo dudaba porque siempre en las clases, si haciamos una solucion muy expresiva, o sea, con mas codigo, lo mejor era hacerla mas declarativa, con menos codigo, obvio, para poder aprovechar todas las herramientas del paradigma. pero puede ser, que como vos decis, no necesariamente este relacionado con el tema declarativo expresivo. podes ser declarativo y tener mas codigo, y eso implica, por ejemplo, delegar y esas cosas. asi que puede serr
