### ISSUE TITLE
Ojota con los parámetros 

### ISSUE THREAD

**Issue by karengrams** [karengrams/FinalesDeParadigmasDeProgramacion#4]
https://github.com/karengrams/FinalesDeParadigmasDeProgramacion/blob/c3ca92361c29dc6287ba92303f05d91f27b0dcf5/27%20de%20septimebre%20del%202017/270917.hs#L13

¿No le falta un "3" ahi? 

> (...) Contando con una función envejecer/2, que recibe una cantidad de años y una persona y devuelve a una persona envejecida en dicha cantidad de años (...)

**Comment by PabloOve** [comment]
que boludoo cierto, mala mia
