### ISSUE TITLE
¿Para todos? ¿No será un encontrar a todos?

### ISSUE THREAD

**Issue by karengrams** [karengrams/FinalesDeParadigmasDeProgramacion#9]
https://github.com/karengrams/FinalesDeParadigmasDeProgramacion/blob/c3ca92361c29dc6287ba92303f05d91f27b0dcf5/27%20de%20septimebre%20del%202017/270917.hs#L56-L58

> 1) Completar ambas soluciones, implementando los predicados que permitan:
>        **a) conocer el conjunto de _personas_ mayores de edad de un lugar**
>        b) obtener una de las personas mayores de edad de un lugar
> Analizando ambas soluciones ¿cuál te parece mejor? Justificar.

**Comment by PabloOve** [comment]
findall yep, mala mia
